# Run from the repository root:
#   docker compose -f docker/docker-compose.yml run --rm mncore-sdk

services:
  mncore-sdk:
    image: kaityo256/mncore-sdk-sample
    pull_policy: missing
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../examples:/root/examples
    working_dir: /root/examples
    stdin_open: true
    tty: true
    command: /bin/bash
